#!/bin/sh
#
# This script does some one-time tasks when the snap is installed for the first
# time.  After the first install, it will not be run again for version upgrades
# unless the snap is completely removed and reinstalled.
#


KEY_DIR="$SNAP_COMMON/keys"


# Generate a private key for the node. This will be used for SSH access to git
# repositories and other authentication purposes.
if [ ! -f "$KEY_DIR/node.key" ]; then
    mkdir -p "$KEY_DIR"

    openssl genrsa -out "$KEY_DIR/node.key" 4096
    chmod 400 "$KEY_DIR/node.key"

    ssh-keygen -y -f "$KEY_DIR/node.key" >"$KEY_DIR/node.pub"
fi


# Initialize snap settings.
#
# This command sets some state for snapd, which will be used later on
# by our configure hook to initialize the settings.ini file.
#
# It is better to call snapctl once with all of the settings rather than
# multiple times. That way only triggers our configure hook once.
snapctl set base.concurrent-builds=true \
            base.debug-mode=false \
            base.dynamic-network-pool=10.128.0.0/9 \
            base.local-domain=paradrop.io
